### ISSUE TITLE
Error on invalid HTML

### ISSUE THREAD

**Issue by adamzap** [Crossway/antimarkdown#10]
This generates an `IndexError`:

```python
antimarkdown.to_markdown('<span><ul><li>abcd</li></ul><li>efgh</li></span>')
```

**Comment by eykd** [comment]
Specific traceback was:

```
      Traceback (most recent call last):
        File "/Users/deyk/code/py/antimarkdown/antimarkdown/__init__.py", line 21, in to_markdown
          return handlers.render(*parse_fragments(html_string, safe_tags))
        File "/Users/deyk/code/py/antimarkdown/antimarkdown/handlers.py", line 16, in render
          lines = str(root).rstrip().splitlines()
        File "/Users/deyk/code/py/antimarkdown/antimarkdown/nodes.py", line 60, in __str__
          return normalize(''.join(str(node) for node in self))
        File "/Users/deyk/code/py/antimarkdown/antimarkdown/nodes.py", line 60, in <genexpr>
          return normalize(''.join(str(node) for node in self))
        File "/Users/deyk/code/py/antimarkdown/antimarkdown/nodes.py", line 74, in __str__
          text = self.text()
        File "/Users/deyk/code/py/antimarkdown/antimarkdown/nodes.py", line 83, in text
          ''.join(str(node) for node in self),
        File "/Users/deyk/code/py/antimarkdown/antimarkdown/nodes.py", line 83, in <genexpr>
          ''.join(str(node) for node in self),
        File "/Users/deyk/code/py/antimarkdown/antimarkdown/nodes.py", line 74, in __str__
          text = self.text()
        File "/Users/deyk/code/py/antimarkdown/antimarkdown/nodes.py", line 205, in text
          li = self.blackboard.get('li-style', ['*   '])[-1]
      IndexError: list index out of range
```
